openapi: "3.0.1"
info:
  version: 1.0.0
  title: Teamwheel API
  contact:
    name: Nils Wöhler
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /api/heroes:
    get:
      description: |
        Returns all heroes
      operationId: getAllHeroes
      responses:
        '200':
          description: heroes response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Heroes'
  /api/heroes/{id}:
    get:
      description: Returns a hero based on a single ID
      operationId: find hero by id
      parameters:
        - name: id
          in: path
          description: ID of hero to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: hero response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
components:
  schemas:
    Heroes:
      required:
        - heroes
      properties:
        heroes:
          type: array
          items:
            $ref: '#/components/schemas/Hero'
    Hero:
      required:
        - id
        - heroName
      properties:
        id:
          type: integer
          format: int64
        heroName:
          type: string